#!/usr/bin/env bash
# train.sh — launch EOLLM training in a detachable GNU screen session.
#
# Uses `screen` (not `tmux`): tmux 3.6 from conda-forge segfaults against the
# system libevent on this CentOS/RHEL 9 kernel. screen 4.8 from conda-forge
# has no such issue and is a strict superset of what we need.
#
# Subcommands:
#   ./train.sh start [flags...]   launch training
#   ./train.sh attach             attach to the screen session
#   ./train.sh status             show session + tail of log + GPU
#   ./train.sh tail               follow the current log (Ctrl-C to stop)
#   ./train.sh stop               kill the training session (graceful)
#   ./train.sh logs               list all training logs
#
# Env vars you can set before `./train.sh start`:
#   NUM_EPOCHS=3            override default epochs
#   LEARNING_RATE=1e-4      override profile default
#   SMOKE_TEST=1            5-step smoke test
#   REPORT_TO=wandb         enable W&B (needs WANDB_API_KEY)
#   EARLY_STOPPING=1        enable early stopping (patience=2)
#   GPU_PROFILE=...         force profile instead of auto-detect
#   BATCH_SAFETY_FRAC=0.70  tighten VRAM safety margin (default 0.80)
#
# screen cheatsheet:
#   Attach:       ./train.sh attach   (or: screen -r eollm_train)
#   Detach:       Ctrl-a d            (keeps training running in background)
#   Scroll:       Ctrl-a ESC, then PgUp/PgDn, ESC to exit scroll mode
#   Quit inside:  Ctrl-a k (asks confirm)  or just exit the shell

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

SESSION="${SESSION:-eollm_train}"
CONDA_ENV="${CONDA_ENV:-unsloth}"
TOOLS_ENV="${TOOLS_ENV:-tools}"
LOGS_DIR="${SCRIPT_DIR}/logs"
PID_FILE="${LOGS_DIR}/train.pid"
CURRENT_LOG_LINK="${LOGS_DIR}/current.log"

mkdir -p "${LOGS_DIR}"

# --- helpers ---

load_modules() {
    module load conda/latest cuda/13.0.2 2>/dev/null || {
        echo "ERROR: 'module load' failed. Is this the lab workstation?" >&2
        exit 1
    }
}

screen_bin() {
    command -v conda >/dev/null 2>&1 || {
        echo "ERROR: conda not initialized. Run: module load conda/latest" >&2
        exit 1
    }
    local prefix
    prefix="$(conda env list | awk -v n="${TOOLS_ENV}" '$1 == n { for (i=2;i<=NF;i++) if ($i ~ /^\//) { print $i; exit } }')"
    [[ -n "${prefix}" ]] || { echo "ERROR: conda env '${TOOLS_ENV}' not found. Run remote_setup.sh." >&2; exit 1; }
    local s="${prefix}/bin/screen"
    [[ -x "${s}" ]] || { echo "ERROR: screen not found at ${s}. Run remote_setup.sh." >&2; exit 1; }
    echo "${s}"
}

session_exists() {
    local SCREEN_BIN; SCREEN_BIN="$(screen_bin)"
    "${SCREEN_BIN}" -ls 2>/dev/null | grep -qE "\.${SESSION}[[:space:]]"
}

# --- subcommands ---

cmd_start() {
    load_modules

    local SCREEN_BIN; SCREEN_BIN="$(screen_bin)"

    if session_exists; then
        echo "ERROR: screen session '${SESSION}' already running." >&2
        echo "  Attach:  ./train.sh attach" >&2
        echo "  Or stop: ./train.sh stop" >&2
        exit 1
    fi

    local ts log runner
    ts="$(date +%Y%m%d_%H%M%S)"
    log="${LOGS_DIR}/training_${ts}.log"
    runner="${LOGS_DIR}/.runner_${ts}.sh"

    # Update 'current' symlink for easy tailing.
    ln -sfn "${log}" "${CURRENT_LOG_LINK}"

    # Generate a runner script — tmux-quoting hell is gone by writing the
    # command to a file and asking screen to execute that. The runner does
    # its own `tee` to the log file so `screen -r` shows live output AND
    # the log file is complete if you never attach.
    cat > "${runner}" <<RUNNER_EOF
#!/usr/bin/env bash
# Auto-generated by train.sh at ${ts}.
set -uo pipefail

# Pipe everything through tee from the start so the log captures all output,
# including 'module load' and 'conda activate' noise.
exec > >(tee -a "${log}") 2>&1

module load conda/latest cuda/13.0.2 2>/dev/null
source "\$(conda info --base)/etc/profile.d/conda.sh"
conda activate ${CONDA_ENV}
cd "${SCRIPT_DIR}"

echo "=========================================================="
echo "Host:       \$(hostname)"
echo "Time:       \$(date)"
echo "GPU:        \$(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader)"
echo "Python:     \$(python --version)"
echo "Log:        ${log}"
echo "Env vars:   NUM_EPOCHS=\${NUM_EPOCHS:-unset}  SMOKE_TEST=\${SMOKE_TEST:-0}  REPORT_TO=\${REPORT_TO:-none}  EARLY_STOPPING=\${EARLY_STOPPING:-0}"
echo "=========================================================="
echo

python -u training/train.py
rc=\$?

echo
echo "=== train.py exited with status \$rc at \$(date) ==="
echo "Session will remain open for 60 seconds so you can read output. Ctrl-a d to detach, Ctrl-a k to kill."
sleep 60
exit \$rc
RUNNER_EOF
    chmod +x "${runner}"

    # Build env-var prefix for the screen command. screen doesn't have `-e`
    # like tmux, so we inline the exports inside the runner call.
    local env_export=""
    for v in NUM_EPOCHS LEARNING_RATE SMOKE_TEST REPORT_TO WANDB_API_KEY WANDB_PROJECT GPU_PROFILE DATASET_DIR BASE_MODEL SEED MAX_STEPS EARLY_STOPPING BATCH_SAFETY_FRAC SPLIT_STRATEGY OUTPUT_DIR SKIP_PROBE BATCH_SIZE WARMUP_STEPS LR_SCHEDULER OPTIM EXCLUDE_TOPICS; do
        if [[ -n "${!v:-}" ]]; then
            # printf %q handles quoting safely for any value
            env_export+="export ${v}=$(printf '%q' "${!v}"); "
        fi
    done

    # Launch. -dm = detached daemon, -S = session name, -L = enable log
    # file (screen's own log, separate from our tee). The command is a bash
    # -lc invocation so the exports land before the runner runs.
    echo "Starting screen session '${SESSION}'..."
    "${SCREEN_BIN}" -dmS "${SESSION}" bash -lc "${env_export}exec '${runner}'"

    # Give screen a moment to actually create the session
    sleep 1
    if ! session_exists; then
        echo "ERROR: screen session '${SESSION}' failed to start." >&2
        echo "  Check runner:  cat ${runner}" >&2
        echo "  Check log:     cat ${log}" >&2
        exit 1
    fi

    echo "$$" > "${PID_FILE}"
    echo
    echo "Training launched."
    echo "  Log:     ${log}"
    echo "  Symlink: ${CURRENT_LOG_LINK}"
    echo "  Runner:  ${runner}"
    echo
    echo "Monitor:"
    echo "  ./train.sh attach    # interactive (Ctrl-a d to detach)"
    echo "  ./train.sh tail      # follow the log"
    echo "  ./train.sh status    # quick glance"
    echo "  ./train.sh stop      # kill the session"
}

cmd_attach() {
    load_modules
    local SCREEN_BIN; SCREEN_BIN="$(screen_bin)"
    if ! session_exists; then
        echo "No active session '${SESSION}'. Start one with: ./train.sh start" >&2
        exit 1
    fi
    echo "Attaching to '${SESSION}'. Detach with Ctrl-a d."
    # -x = multi-attach (safe to attach from multiple shells), -r = attach
    exec "${SCREEN_BIN}" -x "${SESSION}"
}

cmd_status() {
    load_modules
    local SCREEN_BIN; SCREEN_BIN="$(screen_bin)"
    echo "=== screen ==="
    if session_exists; then
        "${SCREEN_BIN}" -ls | grep -E "\.${SESSION}[[:space:]]" || true
        echo "RUNNING"
    else
        echo "NOT RUNNING"
    fi
    echo
    echo "=== current log ==="
    if [[ -L "${CURRENT_LOG_LINK}" ]]; then
        echo "→ $(readlink "${CURRENT_LOG_LINK}")"
        echo
        echo "--- last 30 lines ---"
        tail -30 "${CURRENT_LOG_LINK}" 2>/dev/null || echo "(log not readable)"
    else
        echo "(no current log symlink)"
    fi
    echo
    echo "=== GPU ==="
    nvidia-smi --query-gpu=name,utilization.gpu,memory.used,memory.total,temperature.gpu --format=csv,noheader 2>/dev/null || echo "(nvidia-smi failed)"
}

cmd_tail() {
    [[ -L "${CURRENT_LOG_LINK}" ]] || { echo "No current log." >&2; exit 1; }
    echo "Tailing $(readlink "${CURRENT_LOG_LINK}")  (Ctrl-C to stop)"
    tail -F "${CURRENT_LOG_LINK}"
}

cmd_stop() {
    load_modules
    local SCREEN_BIN; SCREEN_BIN="$(screen_bin)"
    if ! session_exists; then
        echo "No active session '${SESSION}'."
        exit 0
    fi
    echo "Killing screen session '${SESSION}'..."
    "${SCREEN_BIN}" -S "${SESSION}" -X quit
    rm -f "${PID_FILE}"
    echo "Done. Log is preserved at: $(readlink "${CURRENT_LOG_LINK}" 2>/dev/null || echo '(none)')"
}

cmd_logs() {
    echo "Training logs in ${LOGS_DIR}:"
    ls -lh "${LOGS_DIR}"/training_*.log 2>/dev/null || echo "(none)"
    echo
    [[ -L "${CURRENT_LOG_LINK}" ]] && echo "Current → $(readlink "${CURRENT_LOG_LINK}")"
}

# GPU-waiter: poll nvidia-smi, launch training when the GPU is free.
#   MIN_FREE_GB         minimum free VRAM (GB) to consider the GPU free (default 85)
#   STABLE_POLLS        consecutive polls that must satisfy the threshold (default 3)
#   POLL_INTERVAL       seconds between polls                             (default 60)
#   MAX_WAIT_HRS        abort after this many hours (0 = forever)         (default 24)
#   MAX_SMI_FAILS       consecutive nvidia-smi failures before aborting   (default 15)
#   HEARTBEAT_SECS      log a "still waiting" line every N seconds even   (default 600)
#                       when the GPU is busy (prevents silent logs)
#   CLEAR_COMPILE_CACHE 1 to delete unsloth_compiled_cache before launch  (default 1)
# Env vars passed through to train.sh start are forwarded (NUM_EPOCHS etc).
WATCH_SESSION="${WATCH_SESSION:-eollm_watch}"
cmd_watch() {
    load_modules
    local SCREEN_BIN; SCREEN_BIN="$(screen_bin)"

    if "${SCREEN_BIN}" -ls 2>/dev/null | grep -qE "\.${WATCH_SESSION}[[:space:]]"; then
        echo "ERROR: watcher session '${WATCH_SESSION}' already running." >&2
        echo "  Attach:  ${SCREEN_BIN} -x ${WATCH_SESSION}" >&2
        echo "  Or kill: ./train.sh unwatch" >&2
        exit 1
    fi
    if session_exists; then
        echo "ERROR: training session '${SESSION}' already running. Stop it first." >&2
        exit 1
    fi

    # Validate user-facing int env vars early — typos like "MIN_FREE_GB=85x"
    # would otherwise only surface mid-poll via arithmetic errors.
    local intvar
    for intvar in MIN_FREE_GB STABLE_POLLS POLL_INTERVAL MAX_WAIT_HRS MAX_SMI_FAILS HEARTBEAT_SECS; do
        local val="${!intvar:-}"
        if [[ -n "${val}" && ! "${val}" =~ ^[0-9]+$ ]]; then
            echo "ERROR: ${intvar}='${val}' is not a non-negative integer." >&2
            exit 2
        fi
    done
    if [[ -n "${BATCH_SIZE:-}" && ! "${BATCH_SIZE}" =~ ^[0-9]+$ ]]; then
        echo "ERROR: BATCH_SIZE='${BATCH_SIZE}' is not an integer." >&2; exit 2
    fi
    if [[ "${SKIP_PROBE:-0}" == "1" && -z "${BATCH_SIZE:-}" ]]; then
        echo "ERROR: SKIP_PROBE=1 requires BATCH_SIZE=<n>." >&2; exit 2
    fi

    # nvidia-smi must be available right now — no point starting the waiter
    # if the driver is broken. Also probes timeout behavior of the binary.
    if ! timeout 10 nvidia-smi --query-gpu=memory.free --format=csv,noheader,nounits >/dev/null 2>&1; then
        echo "ERROR: nvidia-smi does not respond (driver broken or GPU missing)." >&2
        exit 2
    fi

    local ts log runner
    ts="$(date +%Y%m%d_%H%M%S)"
    log="${LOGS_DIR}/watch_${ts}.log"
    runner="${LOGS_DIR}/.watch_runner_${ts}.sh"

    # Write runner to disk with exports baked in — avoids quoting hell.
    # Uses a "quoted" heredoc so $vars are literal; we substitute only the
    # three paths we need (log, runner, script_dir) via sed afterwards.
    cat > "${runner}" <<'WATCH_EOF'
#!/usr/bin/env bash
# Auto-generated by train.sh watch. Runs inside a screen session; tees to log.
set -uo pipefail
exec > >(tee -a "__LOG__") 2>&1

MIN_FREE_GB="${MIN_FREE_GB:-85}"
STABLE_POLLS="${STABLE_POLLS:-3}"
POLL_INTERVAL="${POLL_INTERVAL:-60}"
MAX_WAIT_HRS="${MAX_WAIT_HRS:-24}"
MAX_SMI_FAILS="${MAX_SMI_FAILS:-15}"
HEARTBEAT_SECS="${HEARTBEAT_SECS:-600}"
CLEAR_COMPILE_CACHE="${CLEAR_COMPILE_CACHE:-1}"

max_wait_s=$(( MAX_WAIT_HRS * 3600 ))   # 0 → forever (handled below)

log_line() { echo "[$(date +%Y-%m-%d' '%H:%M:%S)] $*"; }

trap 'log_line "SIGTERM/SIGINT received — aborting waiter"; exit 130' INT TERM

log_line "=== GPU waiter started (pid=$$) ==="
log_line "  MIN_FREE_GB=${MIN_FREE_GB}  STABLE_POLLS=${STABLE_POLLS}  POLL_INTERVAL=${POLL_INTERVAL}s"
log_line "  MAX_WAIT=$( ((MAX_WAIT_HRS == 0)) && echo forever || echo "${MAX_WAIT_HRS}h")  MAX_SMI_FAILS=${MAX_SMI_FAILS}  HEARTBEAT=${HEARTBEAT_SECS}s"
log_line "  CLEAR_COMPILE_CACHE=${CLEAR_COMPILE_CACHE}"
log_line "  Will forward to: train.sh start (NUM_EPOCHS=${NUM_EPOCHS:-unset} EARLY_STOPPING=${EARLY_STOPPING:-0} SKIP_PROBE=${SKIP_PROBE:-0} BATCH_SIZE=${BATCH_SIZE:-unset})"
echo

# Abort early if another training session is already alive — don't race
# with it. Check the train.sh session via its grep marker (not a load_modules
# path — module load already happened in the parent).
session_check() {
    local screen_bin="__SCREEN_BIN__"
    [[ -x "${screen_bin}" ]] || return 1   # unknown = assume no session
    "${screen_bin}" -ls 2>/dev/null | grep -qE "\.eollm_train[[:space:]]"
}

consecutive=0
elapsed=0
smi_fails=0
last_heartbeat=0

while :; do
    if (( max_wait_s > 0 && elapsed >= max_wait_s )); then
        log_line "=== MAX_WAIT=${MAX_WAIT_HRS}h exceeded — giving up ==="
        exit 1
    fi

    if session_check; then
        log_line "A training session 'eollm_train' is already running — aborting waiter."
        exit 0
    fi

    # Single nvidia-smi query: free, used, total MiB + compute-apps count
    smi_out="$(timeout 10 nvidia-smi --query-gpu=memory.free,memory.used,memory.total --format=csv,noheader,nounits 2>/dev/null | head -1)"
    n_apps="$(timeout 10 nvidia-smi --query-compute-apps=pid --format=csv,noheader 2>/dev/null | grep -cE '^[0-9]+')"

    free_mib="$(echo "${smi_out}" | awk -F',' '{gsub(/ /,""); print $1}')"
    used_mib="$(echo "${smi_out}" | awk -F',' '{gsub(/ /,""); print $2}')"
    total_mib="$(echo "${smi_out}" | awk -F',' '{gsub(/ /,""); print $3}')"

    if [[ ! "${free_mib}" =~ ^[0-9]+$ ]]; then
        smi_fails=$(( smi_fails + 1 ))
        log_line "nvidia-smi failed (${smi_fails}/${MAX_SMI_FAILS}) — treating as busy"
        if (( smi_fails >= MAX_SMI_FAILS )); then
            log_line "=== ${MAX_SMI_FAILS} consecutive nvidia-smi failures — aborting waiter ==="
            exit 1
        fi
        consecutive=0
        sleep "${POLL_INTERVAL}"; elapsed=$(( elapsed + POLL_INTERVAL )); continue
    fi
    smi_fails=0

    free_gb=$(( free_mib / 1024 ))
    used_gb=$(( used_mib / 1024 ))

    if (( free_gb >= MIN_FREE_GB )); then
        consecutive=$(( consecutive + 1 ))
        log_line "free=${free_gb}GB used=${used_gb}GB apps=${n_apps} — OK (${consecutive}/${STABLE_POLLS})"
        if (( consecutive >= STABLE_POLLS )); then
            echo
            log_line "=== GPU free for ${STABLE_POLLS} polls — launching training ==="
            if [[ "${CLEAR_COMPILE_CACHE}" == "1" ]]; then
                log_line "Clearing ~/training/unsloth_compiled_cache to avoid stale-cache dynamo crash..."
                rm -rf "__SCRIPT_DIR__/unsloth_compiled_cache" 2>/dev/null || true
            fi
            # Re-check session once more under the gun (TOCTOU guard)
            if session_check; then
                log_line "Lost the race — training session appeared while we were launching. Exiting."
                exit 0
            fi
            exec bash "__SCRIPT_DIR__/train.sh" start
        fi
    else
        consecutive=0
        # Heartbeat: even a silent "busy" channel shouldn't go quiet for long.
        # We always print on state changes; only HEARTBEAT_SECS spacing filters
        # the "still busy" chatter. Force a line every HEARTBEAT_SECS.
        if (( elapsed - last_heartbeat >= HEARTBEAT_SECS )); then
            log_line "free=${free_gb}GB used=${used_gb}GB apps=${n_apps} — busy (need ${MIN_FREE_GB}GB), still waiting (elapsed=$((elapsed/60))m)"
            last_heartbeat=${elapsed}
        fi
    fi

    sleep "${POLL_INTERVAL}"
    elapsed=$(( elapsed + POLL_INTERVAL ))
done
WATCH_EOF

    # Substitute the paths (done AFTER heredoc so we avoid quoting issues).
    sed -i \
        -e "s|__LOG__|${log}|g" \
        -e "s|__SCRIPT_DIR__|${SCRIPT_DIR}|g" \
        -e "s|__SCREEN_BIN__|${SCREEN_BIN}|g" \
        "${runner}"
    chmod +x "${runner}"

    local env_export=""
    for v in NUM_EPOCHS LEARNING_RATE SMOKE_TEST REPORT_TO WANDB_API_KEY WANDB_PROJECT \
             GPU_PROFILE DATASET_DIR BASE_MODEL SEED MAX_STEPS EARLY_STOPPING \
             BATCH_SAFETY_FRAC SPLIT_STRATEGY OUTPUT_DIR SKIP_PROBE BATCH_SIZE \
             MIN_FREE_GB STABLE_POLLS POLL_INTERVAL MAX_WAIT_HRS MAX_SMI_FAILS \
             HEARTBEAT_SECS CLEAR_COMPILE_CACHE; do
        if [[ -n "${!v:-}" ]]; then
            env_export+="export ${v}=$(printf '%q' "${!v}"); "
        fi
    done

    ln -sfn "${log}" "${LOGS_DIR}/current_watch.log"

    echo "Starting GPU-waiter session '${WATCH_SESSION}'..."
    "${SCREEN_BIN}" -dmS "${WATCH_SESSION}" bash -lc "${env_export}exec '${runner}'"
    sleep 1
    if ! "${SCREEN_BIN}" -ls 2>/dev/null | grep -qE "\.${WATCH_SESSION}[[:space:]]"; then
        echo "ERROR: watcher failed to start — check ${runner}" >&2
        exit 1
    fi
    echo
    echo "Waiter launched. Polling every ${POLL_INTERVAL:-60}s; launches when ≥${MIN_FREE_GB:-85}GB free for ${STABLE_POLLS:-3} polls."
    echo "  Log:      ${log}"
    echo "  Symlink:  ${LOGS_DIR}/current_watch.log"
    echo "  Attach:   ${SCREEN_BIN} -x ${WATCH_SESSION}   (Ctrl-a d to detach)"
    echo "  Tail:     tail -F ${LOGS_DIR}/current_watch.log"
    echo "  Cancel:   ./train.sh unwatch"
}

cmd_unwatch() {
    load_modules
    local SCREEN_BIN; SCREEN_BIN="$(screen_bin)"
    if ! "${SCREEN_BIN}" -ls 2>/dev/null | grep -qE "\.${WATCH_SESSION}[[:space:]]"; then
        echo "No active watcher '${WATCH_SESSION}'."
        exit 0
    fi
    echo "Killing watcher '${WATCH_SESSION}'..."
    "${SCREEN_BIN}" -S "${WATCH_SESSION}" -X quit
    echo "Done."
}

# --- dispatch ---

case "${1:-}" in
    start)   shift; cmd_start "$@" ;;
    attach)  cmd_attach ;;
    status)  cmd_status ;;
    tail)    cmd_tail ;;
    stop)    cmd_stop ;;
    logs)    cmd_logs ;;
    watch)   cmd_watch ;;
    unwatch) cmd_unwatch ;;
    ""|help|-h|--help)
        sed -n '2,36p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'
        ;;
    *)
        echo "Unknown subcommand: $1" >&2
        echo "Run './train.sh help' for usage." >&2
        exit 2
        ;;
esac
