"""
Diverse question templates for the Urban VQA pipeline.
Each topic has 10 natural paraphrases of the same underlying question.
Used by 05_generate_questions.py to randomly select a phrasing per sample,
ensuring linguistic diversity across the dataset.
"""

QUESTION_TEMPLATES = {
    "land_use": [
        "What is the primary land use character of this area?",
        "Based on the imagery, what best describes how this area is primarily used?",
        "Looking at the satellite and street views, classify the dominant land use type.",
        "What type of urban zone does this location represent?",
        "How would you categorize the primary function of this neighborhood?",
        "From the satellite and street-level imagery, what is the predominant land use here?",
        "What kind of area is this — residential, commercial, industrial, or something else?",
        "Considering both the aerial view and the street-level perspective, how is this land primarily utilized?",
        "Which land use category most accurately describes this location?",
        "What is the dominant character of this area in terms of how the land is used?",
    ],
    "building_height": [
        "What building height category best describes the dominant structures in this area?",
        "Based on the satellite and street-level imagery, how tall are most buildings here?",
        "Looking at this location, what is the predominant building height range?",
        "How would you classify the typical building height in this area?",
        "What height category do the majority of structures in this neighborhood fall into?",
        "From the imagery provided, are the buildings here mostly low-rise, mid-rise, or high-rise?",
        "Considering the visible structures, which building height classification fits this area best?",
        "What is the dominant vertical scale of the built environment at this location?",
        "How many stories do the typical buildings in this area appear to have?",
        "Based on the views shown, what best describes the building heights in this neighborhood?",
    ],
    "urban_density": [
        "What is the approximate urban density level of this area based on building concentration?",
        "How densely built-up is this area?",
        "Based on the satellite and street views, what level of urban density does this location exhibit?",
        "Looking at the concentration of buildings, how would you characterize the density here?",
        "From the imagery, is this area sparsely developed, moderately built, or densely packed?",
        "What best describes the building density and urban development intensity of this location?",
        "How would you rate the level of urban development concentration in this neighborhood?",
        "Considering the aerial and ground-level views, what density category fits this area?",
        "Is the built environment here sparse, moderate, dense, or very dense?",
        "What level of building concentration is visible in this area?",
    ],
    "road_type": [
        "What type of road infrastructure is dominant at this location?",
        "Based on the street-level imagery, what kind of road is this?",
        "Looking at the road visible in the images, how would you classify it?",
        "What category of road infrastructure does this location primarily feature?",
        "From the imagery, is this a highway, arterial road, collector road, or local street?",
        "How would you describe the main road type visible at this location?",
        "What is the dominant road classification at this point based on the views provided?",
        "Considering the road width, markings, and surroundings, what type of road is shown?",
        "Based on the satellite and street-level views, what road infrastructure category applies here?",
        "What best describes the road that runs through this location?",
    ],
    "green_space": [
        "Is there publicly accessible green space or parkland near this location?",
        "Based on the imagery, are there parks or green areas visible near this location?",
        "Looking at the satellite and street views, is public green space present in the vicinity?",
        "Does this area have any nearby parks, gardens, or publicly accessible green space?",
        "From the aerial and ground-level views, is there noticeable green space or parkland nearby?",
        "Can you identify any public parks or recreational green areas near this location?",
        "Is there evidence of accessible green space or parkland in this neighborhood?",
        "How would you characterize the availability of public green space around this location?",
        "Based on the views provided, does this area include or border any parks or green areas?",
        "Are parks or public green spaces a feature of this location's immediate surroundings?",
    ],
    "amenity_richness": [
        "What is the level of commercial amenity presence in this area?",
        "Based on the imagery, how rich is this area in shops, restaurants, and services?",
        "Looking at the street views and satellite image, how commercially active is this location?",
        "How would you describe the concentration of commercial amenities in this neighborhood?",
        "From the visible signage and storefronts, what level of amenity presence does this area have?",
        "Is this area well-served by commercial establishments like shops, cafes, and services?",
        "What best describes the density of commercial and service amenities at this location?",
        "Considering the imagery, would you say the commercial amenity presence here is minimal, low, moderate, or high?",
        "How commercially developed is this area in terms of available shops, dining, and services?",
        "Based on the satellite and street-level views, what level of commercial activity is present?",
    ],
}
