"""
Diverse question templates for the Urban VQA pipeline.
Each topic has 10 natural paraphrases of the same underlying question.
Used by 05_generate_questions.py to randomly select a phrasing per sample,
ensuring linguistic diversity across the dataset.
"""

QUESTION_TEMPLATES = {
    "land_use": [
        "What is the primary land use character of this area?",
        "Based on the imagery, what best describes how this area is primarily used?",
        "Looking at the satellite and street views, classify the dominant land use type.",
        "What type of urban zone does this location represent?",
        "How would you categorize the primary function of this neighborhood?",
        "From the satellite and street-level imagery, what is the predominant land use here?",
        "What kind of area is this — residential, commercial, industrial, or something else?",
        "Considering both the aerial view and the street-level perspective, how is this land primarily utilized?",
        "Which land use category most accurately describes this location?",
        "What is the dominant character of this area in terms of how the land is used?",
    ],
    "building_height": [
        "What building height category best describes the dominant structures in this area?",
        "Based on the satellite and street-level imagery, how tall are most buildings here?",
        "Looking at this location, what is the predominant building height range?",
        "How would you classify the typical building height in this area?",
        "What height category do the majority of structures in this neighborhood fall into?",
        "From the imagery provided, are the buildings here mostly low-rise, mid-rise, or high-rise?",
        "Considering the visible structures, which building height classification fits this area best?",
        "What is the dominant vertical scale of the built environment at this location?",
        "How many stories do the typical buildings in this area appear to have?",
        "Based on the views shown, what best describes the building heights in this neighborhood?",
    ],
    "urban_density": [
        "What is the approximate urban density level of this area based on building concentration?",
        "How densely built-up is this area?",
        "Based on the satellite and street views, what level of urban density does this location exhibit?",
        "Looking at the concentration of buildings, how would you characterize the density here?",
        "From the imagery, is this area sparsely developed, moderately built, or densely packed?",
        "What best describes the building density and urban development intensity of this location?",
        "How would you rate the level of urban development concentration in this neighborhood?",
        "Considering the aerial and ground-level views, what density category fits this area?",
        "Is the built environment here sparse, moderate, dense, or very dense?",
        "What level of building concentration is visible in this area?",
    ],
    "road_type": [
        "What type of road infrastructure is dominant at this location?",
        "Based on the street-level imagery, what kind of road is this?",
        "Looking at the road visible in the images, how would you classify it?",
        "What category of road infrastructure does this location primarily feature?",
        "From the imagery, is this a highway, arterial road, collector road, or local street?",
        "How would you describe the main road type visible at this location?",
        "What is the dominant road classification at this point based on the views provided?",
        "Considering the road width, markings, and surroundings, what type of road is shown?",
        "Based on the satellite and street-level views, what road infrastructure category applies here?",
        "What best describes the road that runs through this location?",
    ],
    "green_space": [
        "Is there publicly accessible green space or parkland near this location?",
        "Based on the imagery, are there parks or green areas visible near this location?",
        "Looking at the satellite and street views, is public green space present in the vicinity?",
        "Does this area have any nearby parks, gardens, or publicly accessible green space?",
        "From the aerial and ground-level views, is there noticeable green space or parkland nearby?",
        "Can you identify any public parks or recreational green areas near this location?",
        "Is there evidence of accessible green space or parkland in this neighborhood?",
        "How would you characterize the availability of public green space around this location?",
        "Based on the views provided, does this area include or border any parks or green areas?",
        "Are parks or public green spaces a feature of this location's immediate surroundings?",
    ],
    "amenity_richness": [
        "What is the level of commercial amenity presence in this area?",
        "Based on the imagery, how rich is this area in shops, restaurants, and services?",
        "Looking at the street views and satellite image, how commercially active is this location?",
        "How would you describe the concentration of commercial amenities in this neighborhood?",
        "From the visible signage and storefronts, what level of amenity presence does this area have?",
        "Is this area well-served by commercial establishments like shops, cafes, and services?",
        "What best describes the density of commercial and service amenities at this location?",
        "Considering the imagery, would you say the commercial amenity presence here is minimal, low, moderate, or high?",
        "How commercially developed is this area in terms of available shops, dining, and services?",
        "Based on the satellite and street-level views, what level of commercial activity is present?",
    ],
    "road_surface": [
        "What is the surface type of the main road shown in these images?",
        "Based on the street-level imagery, what material is the road surface made of?",
        "Looking at the road in the images, how would you classify its surface type?",
        "What kind of pavement or surface does the road at this location have?",
        "From the street view, what road surface material is visible?",
        "How would you describe the road surface shown in the imagery?",
        "What type of road surfacing is present at this location?",
        "Considering the street-level view, is the road paved with asphalt, cobblestone, or another material?",
        "Based on the views provided, what surface treatment does the road have?",
        "What best describes the road surface material visible at this location?",
    ],
    "junction_type": [
        "What type of road junction or intersection is shown in these images?",
        "Based on the satellite and street views, what kind of intersection is this?",
        "Looking at this location, how would you classify the road junction type?",
        "What intersection configuration is present at this location?",
        "From the imagery, is this a roundabout, signalized intersection, or another type?",
        "How would you describe the road junction visible in these images?",
        "What type of traffic control or intersection design is shown here?",
        "Considering the satellite and street-level views, what junction type is present?",
        "Based on the road layout visible, what kind of intersection is this?",
        "What best describes the type of road junction at this location?",
    ],
    "water_proximity": [
        "Is there a water body visible near this location in the satellite image?",
        "Based on the imagery, is a river, lake, or canal present near this location?",
        "Looking at the satellite and street views, is water proximity a feature of this area?",
        "Does this location border or sit near a visible water body?",
        "From the satellite image, how close is the nearest water feature to this location?",
        "Is a water body such as a river, canal, or lake visible in the vicinity?",
        "How would you characterize the proximity to water at this location?",
        "Considering the aerial view, is there a water body nearby?",
        "Based on the views provided, is this location near any water features?",
        "Is water proximity a notable characteristic of this location's surroundings?",
    ],
    "transit_density": [
        "What level of public transit stop density exists around this location?",
        "Based on the imagery, how well-served is this area by public transit stops?",
        "Looking at this location, what is the density of nearby transit stops?",
        "How many public transit stops appear to be within walking distance of this location?",
        "From the street-level views, what level of transit infrastructure is visible?",
        "Is this area well-connected by public transit stops such as bus stops or train stations?",
        "What best describes the public transit stop density around this location?",
        "Considering the surroundings, how accessible is public transit from this location?",
        "Based on the imagery, would you say public transit access here is none, low, moderate, or high?",
        "What level of public transportation infrastructure is present near this location?",
    ],
    "camera_direction": [
        "Relative to the satellite image, in which direction is the street view camera pointing?",
        "Looking at the satellite view as a map, which quadrant is the street-level camera facing toward?",
        "Based on the road orientation and satellite image, which direction does the street view look?",
        "In which direction on the satellite image is the street view camera oriented?",
        "Considering the satellite image as a north-up map, where is the street view camera aimed?",
        "Which quadrant of the satellite image corresponds to the direction the street view camera faces?",
        "From the road alignment visible in both views, which way is the street view camera pointing?",
        "Relative to the aerial view, in which cardinal direction is the ground-level camera looking?",
        "Using the satellite image as reference, which direction does the street-level perspective face?",
        "Which part of the satellite image does the street view camera look toward?",
    ],
    "mismatch_binary": [
        "Does this street view image correspond to the satellite image shown?",
        "Are the street view and satellite image from the same location?",
        "Do the street-level and aerial views depict the same place?",
        "Is the street view consistent with the satellite image of this location?",
        "Based on visual cues, do these two views match the same geographic location?",
        "Does the ground-level imagery correspond to what is visible in the satellite view?",
        "Are the street-level and satellite perspectives showing the same area?",
        "Can you confirm that the street view and satellite image are from the same location?",
        "Do the visual features in the street view align with the satellite image?",
        "Is there a match between the street-level and aerial imagery shown?",
    ],
    "mismatch_mcq": [
        "Which of the four satellite images corresponds to the street view location?",
        "Looking at the 2x2 grid of satellite images, which one matches the street view?",
        "Which satellite tile in the grid shows the same location as the street view?",
        "Based on the street-level imagery, which of the four aerial views is the correct match?",
        "Identify which satellite image in the grid corresponds to the street view shown.",
        "Of the four satellite tiles, which one depicts the same area as the street view?",
        "Which quadrant of the satellite grid matches the ground-level perspective?",
        "From the four satellite options, select the one that shows the street view location.",
        "Which of the tiled satellite images best matches the street-level view?",
        "Looking at the composite satellite grid, which tile corresponds to this street view?",
    ],
}
